#!/bin/bash
#
# AI/DLC Pipeline Continuation Hook
#
# PURPOSE
# Enforces Rule 3 (Never stall the pipeline) when the pipeline is in
# autonomous mode. Respects user-initiated pauses by reading a pause
# flag written by the UserPromptSubmit hook (ai-dlc-pause.sh).
#
# DECISION ORDER (first match wins)
# 1. stop_hook_active=true           -> allow stop (loop prevention)
# 2. pause flag exists               -> allow stop (user is driving)
# 3. no snapshot exists              -> allow stop (no active pipeline)
# 4. default                         -> block stop (force Rule 3 continue)
#
# PAUSE CONTRACT
# The pause flag is created by ai-dlc-pause.sh on any user message
# during an active pipeline. The lead interprets the user's intent
# and deletes the flag when the user wants to resume. This hook
# never creates or deletes the flag; it only reads it.
#
# LOOP PREVENTION
# If stop_hook_active is already true in the input, exit 0 and allow
# the stop. Prevents infinite loops where the hook blocks, Claude
# attempts stop again, hook blocks again, ad infinitum.
#
# OUTPUT
# - Appends to: _bmad-output/pipeline-continuation-log.md
# - JSON to stdout on block: decision + reason
# - Exit 0 in all cases (block is in the JSON body)
#
# INSTALL
# 1. Place at .claude/hooks/ai-dlc-continue.sh
# 2. chmod +x .claude/hooks/ai-dlc-continue.sh
# 3. Add to .claude/settings.json hooks:
#      "Stop": [
#        {
#          "hooks": [{
#            "type": "command",
#            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/ai-dlc-continue.sh"
#          }]
#        }
#      ]
# 4. Restart Claude Code
# 5. Verify with /hooks

set -u

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
SNAPSHOT_FILE="${PROJECT_DIR}/_bmad-output/pipeline-snapshot.md"
LOG_DIR="${PROJECT_DIR}/_bmad-output"
LOG_FILE="${LOG_DIR}/pipeline-continuation-log.md"
PAUSE_FLAG="${LOG_DIR}/pipeline-paused.flag"

# -----------------------------------------------------------------------------
# Read hook input
# -----------------------------------------------------------------------------
INPUT=$(cat)
STOP_HOOK_ACTIVE=$(echo "$INPUT" | jq -r '.stop_hook_active // false')
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# -----------------------------------------------------------------------------
# Seed log header if needed
# -----------------------------------------------------------------------------
mkdir -p "$LOG_DIR"
if [ ! -s "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<'EOF'
# Pipeline Flow Log

Records pipeline-level events: user pauses, Rule 3 enforcement,
and loop-prevention backoffs. Generated by AI/DLC hook scripts.

Event types:

- `USER_PAUSE`: user sent a message; pipeline paused via flag file
- `BLOCKED`: Stop event blocked; Rule 3 enforcement forced continue
- `ALLOWED_BY_PAUSE`: Stop event allowed because pause flag exists
- `BACKOFF`: stop_hook_active was true; loop prevention engaged

Retro reviews this log to assess pipeline flow:

- High USER_PAUSE counts mean the user intervened often (normal for
  interactive sprints, concerning if unexpected)
- High BLOCKED counts mean Rule 3 enforcement is doing work; without
  the hook the pipeline would have stalled
- BACKOFF entries indicate the pipeline got stuck and the safety
  valve triggered

---

EOF
fi

# -----------------------------------------------------------------------------
# Check 1: Loop prevention
# -----------------------------------------------------------------------------
if [ "$STOP_HOOK_ACTIVE" = "true" ]; then
  {
    echo "## ${TIMESTAMP} -- BACKOFF"
    echo "- Session: ${SESSION_ID}"
    echo "- stop_hook_active was true; allowing stop to prevent loop"
    echo ""
  } >> "$LOG_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Check 2: Pause flag (user-initiated pause)
# -----------------------------------------------------------------------------
if [ -f "$PAUSE_FLAG" ]; then
  {
    echo "## ${TIMESTAMP} -- ALLOWED_BY_PAUSE"
    echo "- Session: ${SESSION_ID}"
    echo "- Pause flag present; stop allowed"
    echo ""
  } >> "$LOG_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Check 3: No active pipeline
# -----------------------------------------------------------------------------
if [ ! -f "$SNAPSHOT_FILE" ]; then
  exit 0
fi

# -----------------------------------------------------------------------------
# Default: Block the stop. Pipeline is active and autonomous.
# -----------------------------------------------------------------------------

# Extract current step and last gate from snapshot (best-effort).
# Snapshots may format as "current_step_file: <path>" or
# "- **current_step_file:** <path>". No line-start anchor; sed strips
# markdown bullet/bold and the leading label.
CURRENT_STEP=$(grep -iE "(current_step_file|current[ _]step|current[ _]phase)" "$SNAPSHOT_FILE" 2>/dev/null | head -1 | sed 's/^[^:]*://;s/^[-* ]*//;s/[-* ]*$//' || echo "")
LAST_GATE=$(grep -iE "(last_gate_passed|last[ _]gate)" "$SNAPSHOT_FILE" 2>/dev/null | head -1 | sed 's/^[^:]*://;s/^[-* ]*//;s/[-* ]*$//' || echo "")

REASON="Pipeline is active and in autonomous mode. Do not stop. Per SKILL.md Rule 3 (Never stall the pipeline), continue to the next step without waiting for user input."

if [ -n "$CURRENT_STEP" ]; then
  REASON="${REASON} Current step: ${CURRENT_STEP}."
fi
if [ -n "$LAST_GATE" ]; then
  REASON="${REASON} Last gate passed: ${LAST_GATE}."
fi

REASON="${REASON} Read the pipeline snapshot at _bmad-output/pipeline-snapshot.md for full state, then execute the next step file's 'READ AND FOLLOW' directive. If you believe the pipeline should actually pause, the pause flag at _bmad-output/pipeline-paused.flag must be created by a user message; you cannot create it yourself."

{
  echo "## ${TIMESTAMP} -- BLOCKED"
  echo "- Session: ${SESSION_ID}"
  if [ -n "$CURRENT_STEP" ]; then
    echo "- Current step: ${CURRENT_STEP}"
  fi
  if [ -n "$LAST_GATE" ]; then
    echo "- Last gate: ${LAST_GATE}"
  fi
  echo "- Reason returned to Claude: forced continuation (Rule 3)"
  echo ""
} >> "$LOG_FILE"

jq -n \
  --arg reason "$REASON" \
  '{
    decision: "block",
    reason: $reason
  }'

exit 0