#!/bin/bash
#
# AI/DLC Pipeline Pause Hook
#
# PURPOSE
# Pauses the AI/DLC pipeline whenever the user sends a message.
# Creates a flag file that the Stop hook (ai-dlc-continue.sh) reads
# to honor the pause. The lead interprets the user's intent and
# deletes the flag when appropriate (e.g., user wants to resume).
#
# DESIGN CONTRACT
# - Pipeline runs autonomously when no pause flag exists
# - Any user message creates the pause flag
# - The lead deletes the flag to resume autonomous execution
# - Flag deletion is the lead's responsibility, not this hook's
#
# GATING
# Only creates the flag when a pipeline snapshot exists. This prevents
# cluttering non-AI/DLC sessions with flag files. If the user invokes
# /ai-dlc for the first time (no snapshot yet), this hook skips and
# the pipeline starts normally. By the time Claude writes the first
# snapshot, the pipeline is in autonomous mode.
#
# OUTPUT
# - Creates: _bmad-output/pipeline-paused.flag (empty file, acts as
#   signal)
# - Appends to: _bmad-output/pipeline-continuation-log.md
# - stdout: JSON with additionalContext telling the lead what to do
#
# INSTALL
# 1. Place at .claude/hooks/ai-dlc-pause.sh
# 2. chmod +x .claude/hooks/ai-dlc-pause.sh
# 3. Add to .claude/settings.json hooks:
#      "UserPromptSubmit": [
#        {
#          "hooks": [{
#            "type": "command",
#            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/ai-dlc-pause.sh"
#          }]
#        }
#      ]
# 4. Restart Claude Code
# 5. Verify with /hooks

set -u

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
SNAPSHOT_FILE="${PROJECT_DIR}/_bmad-output/pipeline-snapshot.md"
LOG_DIR="${PROJECT_DIR}/_bmad-output"
LOG_FILE="${LOG_DIR}/pipeline-continuation-log.md"
PAUSE_FLAG="${LOG_DIR}/pipeline-paused.flag"

# -----------------------------------------------------------------------------
# Read hook input
# -----------------------------------------------------------------------------
INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
PROMPT_PREVIEW=$(echo "$INPUT" | jq -r '.prompt // empty' | head -c 120 | tr '\n' ' ')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# -----------------------------------------------------------------------------
# Skip if no active pipeline
# -----------------------------------------------------------------------------
if [ ! -f "$SNAPSHOT_FILE" ]; then
  # No snapshot means no active pipeline. Don't create flag.
  # This covers the /ai-dlc invocation case: first message, no snapshot
  # yet, skip. Claude starts the pipeline. By the time snapshot exists,
  # we're in autonomous mode.
  exit 0
fi

# -----------------------------------------------------------------------------
# Pipeline is active. Create pause flag.
# -----------------------------------------------------------------------------
mkdir -p "$LOG_DIR"
touch "$PAUSE_FLAG"

# -----------------------------------------------------------------------------
# Log the pause event
# -----------------------------------------------------------------------------
# Seed log header if this is the first write
if [ ! -s "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<'EOF'
# Pipeline Flow Log

Records pipeline-level events: user pauses, Rule 3 enforcement,
and loop-prevention backoffs. Generated by AI/DLC hook scripts.

Event types:

- `USER_PAUSE`: user sent a message; pipeline paused via flag file
- `BLOCKED`: Stop event blocked; Rule 3 enforcement forced continue
- `ALLOWED_BY_PAUSE`: Stop event allowed because pause flag exists
- `BACKOFF`: stop_hook_active was true; loop prevention engaged

Retro reviews this log to assess pipeline flow:

- High USER_PAUSE counts mean the user intervened often (normal for
  interactive sprints, concerning if unexpected)
- High BLOCKED counts mean Rule 3 enforcement is doing work; without
  the hook the pipeline would have stalled
- BACKOFF entries indicate the pipeline got stuck and the safety
  valve triggered

---

EOF
fi

{
  echo "## ${TIMESTAMP} -- USER_PAUSE"
  echo "- Session: ${SESSION_ID}"
  echo "- Prompt (first 120 chars): ${PROMPT_PREVIEW}"
  echo ""
} >> "$LOG_FILE"

# -----------------------------------------------------------------------------
# Inject context so the lead knows about the pause
# -----------------------------------------------------------------------------
# This fires on every user message during an active pipeline. Keep it
# concise -- the lead sees this as additionalContext before processing
# the user's message.

CONTEXT="[AI/DLC Pipeline Control] A user message was received while the pipeline is active. The pipeline has been paused via flag file at _bmad-output/pipeline-paused.flag. Before continuing pipeline work, interpret the user's intent: (a) Resume intent -- including /ai-dlc invocations, handoff resume prompts, or natural resume language -- delete the flag via Bash (rm _bmad-output/pipeline-paused.flag) then proceed with the next pipeline step. (b) Question, correction, clarification, or conversational message -- respond normally; leave the flag in place. (c) Handoff request -- follow Rule 2 handoff protocol; leave the flag in place. Do not execute pipeline steps while the flag exists."

jq -n \
  --arg context "$CONTEXT" \
  '{
    hookSpecificOutput: {
      hookEventName: "UserPromptSubmit",
      additionalContext: $context
    }
  }'

exit 0