#!/bin/bash
#
# AI/DLC Path Protection Hook
#
# Prevents context-mode MCP tools (ctx_execute_file, ctx_batch_execute)
# from consolidating files that AI/DLC requires to load verbatim.
#
# PROTECTED PATHS (see PROTECTED_PATTERNS below):
# Rule files, pipeline snapshot, gate log, escalations, setup skill.
# Consolidation risks pipeline integrity drift.
#
# INSTALL
# Automated: scripts/install.sh copies this hook and installs
# templates/settings.json.template with both PreToolUse matchers.
# Manual: place at .claude/hooks/ai-dlc-protect.sh, chmod +x, and
# ensure .claude/settings.json includes the context-mode matcher
# from templates/settings.json.template.

set -u

# -----------------------------------------------------------------------------
# Protected paths
# -----------------------------------------------------------------------------

PROTECTED_PATTERNS=(
  ".claude/skills/ai-dlc/SKILL.md"
  ".claude/skills/ai-dlc/steps/*"
  ".claude/skills/ai-dlc/research-citations.md"
  ".claude/skills/ai-dlc-setup/SKILL.md"
  ".claude/team-roles/*.md"
  "CLAUDE.md"
  "SKILL.md"
  "docs/coding-conventions.md"
  "_bmad-output/pipeline-snapshot.md"
  "_bmad-output/implementation-artifacts/gate-log.md"
  "docs/escalations/pending.md"
)

# -----------------------------------------------------------------------------
# Log configuration
# -----------------------------------------------------------------------------
LOG_DIR="${CLAUDE_PROJECT_DIR:-.}/_bmad-output"
LOG_FILE="${LOG_DIR}/context-mode-protection-log.md"

mkdir -p "$LOG_DIR"

if [ ! -s "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<'EOF'
# Context-Mode Path Protection Log

Records every attempt by context-mode MCP tools to consolidate
AI/DLC protected paths. Generated by `.claude/hooks/ai-dlc-protect.sh`.

---

EOF
fi

# -----------------------------------------------------------------------------
# Read hook input
# -----------------------------------------------------------------------------
INPUT=$(cat)

TOOL_NAME=$(echo "$INPUT" | jq -r '.tool_name // empty')
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# -----------------------------------------------------------------------------
# Extract file paths from tool_input
# -----------------------------------------------------------------------------

FILE_PATHS=""

if [ "$TOOL_NAME" = "mcp__plugin_context-mode_context-mode__ctx_execute_file" ]; then
  FILE_PATHS=$(echo "$INPUT" | jq -r '.tool_input.path // empty')
fi

if [ "$TOOL_NAME" = "mcp__plugin_context-mode_context-mode__ctx_batch_execute" ]; then
  FILE_PATHS=$(echo "$INPUT" | jq -r '.tool_input.commands[]? // empty' \
    | grep -oE '(\.claude/[a-zA-Z0-9_./*-]+|_bmad-output/[a-zA-Z0-9_./*-]+|docs/[a-zA-Z0-9_./*-]+|CLAUDE\.md|SKILL\.md)' \
    | sort -u || true)
fi

# -----------------------------------------------------------------------------
# Match against protected patterns
# -----------------------------------------------------------------------------

is_protected() {
  local path="$1"
  path="${path#./}"
  path="${path#"${CLAUDE_PROJECT_DIR:-}"/}"

  for pattern in "${PROTECTED_PATTERNS[@]}"; do
    # shellcheck disable=SC2254
    case "$path" in
      $pattern) return 0 ;;
    esac
  done

  return 1
}

# -----------------------------------------------------------------------------
# Evaluate paths
# -----------------------------------------------------------------------------
PROTECTED_HITS=()
ALL_PATHS=()

if [ -n "$FILE_PATHS" ]; then
  while IFS= read -r path; do
    [ -z "$path" ] && continue
    ALL_PATHS+=("$path")
    if is_protected "$path"; then
      PROTECTED_HITS+=("$path")
    fi
  done <<< "$FILE_PATHS"
fi

# -----------------------------------------------------------------------------
# Log and decide
# -----------------------------------------------------------------------------

if [ ${#PROTECTED_HITS[@]} -gt 0 ]; then
  {
    echo "## ${TIMESTAMP} -- ${TOOL_NAME} -- PROTECTED"
    echo "- Session: ${SESSION_ID}"
    echo "- Decision: deny"
    echo "- Protected paths detected:"
    for p in "${PROTECTED_HITS[@]}"; do
      echo "  - \`${p}\`"
    done
    echo ""
  } >> "$LOG_FILE"

  REASON="AI/DLC protected path(s) detected: $(printf '%s, ' "${PROTECTED_HITS[@]}" | sed 's/, $//'). Use native Read for verbatim content."

  jq -n \
    --arg reason "$REASON" \
    --arg context "This path is protected by AI/DLC integrity rules. Use the native Read tool for verbatim file content. Protected categories: rule files, pipeline snapshot, gate log, escalations." \
    '{
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: $reason,
        additionalContext: $context
      }
    }'

  exit 0
fi

if [ ${#ALL_PATHS[@]} -gt 0 ]; then
  {
    echo "## ${TIMESTAMP} -- ${TOOL_NAME} -- allowed"
    echo "- Session: ${SESSION_ID}"
    echo "- Paths: $(printf '%s, ' "${ALL_PATHS[@]}" | sed 's/, $//')"
    echo ""
  } >> "$LOG_FILE"
fi

exit 0
