#!/bin/bash
#
# AI/DLC Pipeline Continuation Hook
#
# PURPOSE
# Enforces Rule 3 (Never stall the pipeline) when the pipeline is in
# autonomous mode. Respects user-initiated pauses via a flag file
# written by the UserPromptSubmit hook (ai-dlc-pause.sh).
#
# DECISION ORDER (first match wins)
# 1. pause flag exists               -> allow stop (user is driving)
# 2. no snapshot exists              -> allow stop (no active pipeline)
# 3. rapid-fire limit exceeded       -> allow stop (stall confirmed)
# 4. default                         -> block stop (force Rule 3 continue)
#
# RAPID-FIRE DETECTION (time-based, replaces stop_hook_active check)
# Tracks the timestamp of each block and a counter of consecutive
# rapid-fire blocks. If two blocks occur within 30 seconds of each
# other, they are counted as the same stall attempt. After 3 such
# rapid-fire blocks, the hook backs off and allows the stop.
#
# Why time-based instead of stop_hook_active? When the pipeline
# invokes multiple bmad skills in sequence (common in Discovery
# phase: brainstorming, advanced-elicit, adversarial-review),
# each skill's turn ends with a Stop event and Claude Code sets
# stop_hook_active=true on the next turn. The stop_hook_active
# signal cannot distinguish "genuine loop" from "legitimate
# multi-skill progression." A 30-second threshold cleanly
# separates the two: a real bmad skill takes far longer than
# 30 seconds, while a tight stall-and-retry happens in seconds.
#
# PAUSE CONTRACT
# The pause flag is created by:
#   1. ai-dlc-pause.sh on any user message during an active pipeline, OR
#   2. The lead itself when it has a legitimate intentional pause
#      (HARD_BLOCK awaiting operator decision per Rule 11(a), handoff
#      per Rule 2, gate failure, Production Validation Checkpoint).
# The lead interprets user intent and deletes the flag when the user
# wants to resume autonomous execution. This hook never creates or
# deletes the flag; it only reads it.
#
# DESIGN PRINCIPLE
# This hook prevents UNINTENTIONAL stalls. It does not prevent
# INTENTIONAL pauses. The lead has authority to pause when it knows
# it should pause (per AI/DLC rules). The flag file is the lead's
# mechanism to express that intent. The hook respects the flag
# regardless of who created it.
#
# OUTPUT
# - State: _bmad-output/pipeline-block-state.txt (2 lines:
#   last-block epoch timestamp, consecutive rapid-fire count)
# - Appends to: _bmad-output/pipeline-continuation-log.md
# - JSON to stdout on block: decision + reason
# - Exit 0 in all cases (block is in the JSON body)
#
# INSTALL
# 1. Place at .claude/hooks/ai-dlc-continue.sh
# 2. chmod +x .claude/hooks/ai-dlc-continue.sh
# 3. Add to .claude/settings.json hooks:
#      "Stop": [
#        {
#          "hooks": [{
#            "type": "command",
#            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/ai-dlc-continue.sh"
#          }]
#        }
#      ]
# 4. Restart Claude Code
# 5. Verify with /hooks

set -u

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
SNAPSHOT_FILE="${PROJECT_DIR}/_bmad-output/pipeline-snapshot.md"
LOG_DIR="${PROJECT_DIR}/_bmad-output"
LOG_FILE="${LOG_DIR}/pipeline-continuation-log.md"
PAUSE_FLAG="${LOG_DIR}/pipeline-paused.flag"
STATE_FILE="${LOG_DIR}/pipeline-block-state.txt"

# Rapid-fire thresholds
RAPID_WINDOW_SECONDS=30
MAX_RAPID_BLOCKS=3

# -----------------------------------------------------------------------------
# Read hook input
# -----------------------------------------------------------------------------
INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
NOW=$(date +%s)

# -----------------------------------------------------------------------------
# Seed log header if needed
# -----------------------------------------------------------------------------
mkdir -p "$LOG_DIR"
if [ ! -s "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<'EOF'
# Pipeline Flow Log

Records pipeline-level events: user pauses, Rule 3 enforcement, operator
acknowledgement denials, and rapid-fire stall detection. Generated by AI/DLC
hook scripts. Rotated per sprint at retro close (Rule 25(c)).

Event types:

- `USER_PAUSE`: user sent a message; pipeline paused via flag file
- `BLOCKED`: Stop event blocked; Rule 3 enforcement forced continue
- `ALLOWED_BY_PAUSE`: Stop event allowed because pause flag exists
- `ACK_DENIED`: a pipeline-advancing tool call was DENIED because an operator
  message was outstanding and unacknowledged (Rule 29)
- `BACKOFF`: rapid-fire stop attempts detected; stall confirmed

Retro reviews this log to assess pipeline flow:

- High USER_PAUSE counts mean the user intervened often (normal for
  interactive sprints, concerning if unexpected)
- High BLOCKED counts mean Rule 3 enforcement is doing work; without
  the hook the pipeline would have stalled
- BACKOFF entries indicate the pipeline actually got stuck and the
  hook exhausted its retry budget. Investigate the transcript around
  each BACKOFF to find the upstream cause.

---

EOF
fi

# -----------------------------------------------------------------------------
# Check 0: Handoff resume-prompt guard
# -----------------------------------------------------------------------------
# Minimum mechanism (Rule 26(c)).
#   Failure caught: the operator asks for a handoff and the turn ENDS without a
#     copy-pasteable `/ai-dlc resume` block. The successor session then has no
#     entry line and the operator hand-writes one. A prose mandate
#     (`steps/handoff.md` step 4) did not hold on its own; this moves emission to
#     the harness. Presence alone is insufficient — a `/ai-dlc resume` mentioned in
#     prose, or in a blockquote with no delimiter lines, is not copy-pasteable — so
#     the guard checks FORMAT: the command line must sit BETWEEN two delimiter
#     lines.
#   False-positive cost: one extra turn when the operator's message merely mentions
#     handoff without requesting one. It self-clears through the rapid-fire backoff
#     below (MAX_RAPID_BLOCKS), so it can never wedge the pipeline.
#   Removal condition: retire when two consecutive sprints record zero
#     handoff-emission misses, or when the resume block is generated rather than
#     hand-authored.
#
# THE DELIMITER IS `-{4,}`, NOT AN EXACT COUNT, AND THAT IS THE WHOLE LESSON.
# The reference consumer carried this guard for months matching EXACTLY six hyphens
# (`^------$`) while `steps/handoff.md` step 4 has ALWAYS mandated four (`----`).
# Six-hyphen appears nowhere in core, at any sha. So the guard fired on handoffs
# that were CORRECT per the rulebook: the lead emitted `----` as instructed, got
# blocked, read a block message telling it to use `------`, and complied with the
# HOOK instead of the RULE. The enforcer quietly overruled the rule it was written
# to enforce — a check that fires on compliance, which is worse than no check.
# The invariant that matters is "the command line is delimited for copy-paste",
# never the hyphen count. Accept four or more; quote the rulebook's own template.
#
# Fail-open: any transcript parse failure skips this check entirely.
TRANSCRIPT=$(echo "$INPUT" | jq -r '.transcript_path // empty')
HANDOFF_STATE="${LOG_DIR}/handoff-guard-state.txt"
if [ -n "$TRANSCRIPT" ] && [ -f "$TRANSCRIPT" ]; then
  LAST_USER=$(jq -rs '[.[]|select(.message.role=="user")|.message.content|(if type=="string" then . else (map(select(.type=="text")|.text)|join(" ")) end)]|map(select(length>0))|last // ""' "$TRANSCRIPT" 2>/dev/null || echo "")
  # LAST_ASST is reconstructed with join("") (NOT " "): the format check below is
  # line-anchored, and a streaming split of one text block into chunks can land a
  # boundary mid-line — join(" ") then corrupts a `----` marker into `-- --` and the
  # lead's own well-formed block false-blocks. join("") rejoins contiguous text so
  # marker lines survive. LAST_USER keeps join(" ") (substring regex, spacing-tolerant).
  LAST_ASST=$(jq -rs '[.[]|select(.message.role=="assistant")|.message.content|(if type=="string" then . else (map(select(.type=="text")|.text)|join("")) end)]|map(select(length>0))|last // ""' "$TRANSCRIPT" 2>/dev/null || echo "")

  # Match REQUEST-shaped phrasings only — "handoff"/"hand off" as a VERB, a terse
  # standalone "handoff", or "continue in a new session". Do NOT match incidental
  # NOUN mentions ("the handoff prompt", "handoff guard", the injected pipeline-control
  # context): those are discussion, not a request, and a bare-substring regex fires on
  # every one of them and spams the operator with a spurious resume prompt. The second
  # grep excludes any message that IS a resume prompt or talks ABOUT the mechanism.
  if echo "$LAST_USER" | grep -qiE 'hand[ -]off (this|it|to|the (sprint|pipeline|work|session))|hand(ing)? (this|it) off|\b(do|create|prepare|need|want|start|begin|let'\''s|please) (a |an |the )?hand[ -]?off\b|^[[:space:]]*hand[ -]?off[[:space:]]*$|continue in a (new|fresh) session|pick (this|it) up in a (new|fresh) session' \
     && ! echo "$LAST_USER" | grep -qiE '/ai-dlc|acknowledge handoff|handoff (resume|guard|prompt|protocol)|resume prompt|pipeline control'; then

    RESUME_OK=$(printf '%s' "$LAST_ASST" | awk '
      /^[[:space:]]*-{4,}[[:space:]]*$/ { marks++; if (marks==1){opened=1;sawcmd=0} else if (marks>=2 && sawcmd){ok=1}; next }
      opened && /^[[:space:]]*\/ai-dlc[[:space:]]+resume[[:space:]]*$/ { sawcmd=1 }
      END { print (ok?"1":"0") }')

    if [ "$RESUME_OK" != "1" ]; then
      H_LAST=0; H_CNT=0
      if [ -f "$HANDOFF_STATE" ]; then
        H_LAST=$(sed -n '1p' "$HANDOFF_STATE" 2>/dev/null); H_CNT=$(sed -n '2p' "$HANDOFF_STATE" 2>/dev/null)
        [[ "$H_LAST" =~ ^[0-9]+$ ]] || H_LAST=0; [[ "$H_CNT" =~ ^[0-9]+$ ]] || H_CNT=0
      fi
      if [ $((NOW - H_LAST)) -lt "$RAPID_WINDOW_SECONDS" ]; then H_CNT=$((H_CNT + 1)); else H_CNT=1; fi
      if [ "$H_CNT" -le "$MAX_RAPID_BLOCKS" ]; then
        echo "$NOW" > "$HANDOFF_STATE"; echo "$H_CNT" >> "$HANDOFF_STATE"
        {
          echo "## ${TIMESTAMP} -- HANDOFF_GUARD_BLOCK (${H_CNT}/${MAX_RAPID_BLOCKS})"
          echo "- Session: ${SESSION_ID}"
          echo "- Handoff requested but the turn ends with no delimited /ai-dlc resume block"
          echo ""
        } >> "$LOG_FILE"
        jq -n --arg r "HANDOFF GUARD: the operator requested a handoff, but this turn ends WITHOUT a copy-pasteable resume prompt. Per steps/handoff.md step 4, emit exactly this, and nothing else -- no narrated body:

\`\`\`
----
/ai-dlc resume
----
\`\`\`

The \`/ai-dlc resume\` line MUST sit BETWEEN two delimiter lines (four or more hyphens, each on its own line). A blockquote is not a delimiter, and a bare mention in prose is not copy-pasteable. Finalize the pipeline snapshot first (step 3) if you have not -- state lives in the snapshot, not the resume line." '{decision:"block",reason:$r,suppressOutput:true}'
        exit 0
      fi
      rm -f "$HANDOFF_STATE"   # backoff exhausted: allow stop (possible false positive)
    else
      rm -f "$HANDOFF_STATE"   # well-formed resume block present: handoff satisfied
    fi
  fi
fi

# -----------------------------------------------------------------------------
# Check 1: Pause flag (user-initiated pause)
# -----------------------------------------------------------------------------
if [ -f "$PAUSE_FLAG" ]; then
  {
    echo "## ${TIMESTAMP} -- ALLOWED_BY_PAUSE"
    echo "- Session: ${SESSION_ID}"
    echo "- Pause flag present; stop allowed"
    echo ""
  } >> "$LOG_FILE"
  # Reset block state -- pause-resume cycle counts as progress
  rm -f "$STATE_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Check 2: No active pipeline
# -----------------------------------------------------------------------------
if [ ! -f "$SNAPSHOT_FILE" ]; then
  # No pipeline; no state to track
  rm -f "$STATE_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Read block state and compute rapid-fire status
# -----------------------------------------------------------------------------
LAST_TS=0
COUNTER=0

if [ -f "$STATE_FILE" ]; then
  LAST_TS=$(sed -n '1p' "$STATE_FILE" 2>/dev/null || echo "0")
  COUNTER=$(sed -n '2p' "$STATE_FILE" 2>/dev/null || echo "0")
  # Defensive: ensure numeric values
  [[ "$LAST_TS" =~ ^[0-9]+$ ]] || LAST_TS=0
  [[ "$COUNTER" =~ ^[0-9]+$ ]] || COUNTER=0
fi

DELTA=$((NOW - LAST_TS))

if [ "$DELTA" -lt "$RAPID_WINDOW_SECONDS" ]; then
  # Within rapid-fire window; same stall attempt
  COUNTER=$((COUNTER + 1))
else
  # Gap > window; progress happened (or first block)
  COUNTER=1
fi

# -----------------------------------------------------------------------------
# Check 3: Rapid-fire limit exceeded (genuine stall)
# -----------------------------------------------------------------------------
if [ "$COUNTER" -gt "$MAX_RAPID_BLOCKS" ]; then
  {
    echo "## ${TIMESTAMP} -- BACKOFF"
    echo "- Session: ${SESSION_ID}"
    echo "- ${MAX_RAPID_BLOCKS} consecutive rapid-fire blocks (within ${RAPID_WINDOW_SECONDS}s of each other); stall confirmed"
    echo "- Allowing stop. Investigate transcript for upstream cause."
    echo ""
  } >> "$LOG_FILE"
  rm -f "$STATE_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Default: Block the stop. Pipeline is active and autonomous.
# -----------------------------------------------------------------------------

# Extract current step and last gate from snapshot (best-effort).
# Snapshots may format as "current_step_file: <path>" or
# "- **current_step_file:** <path>". No line-start anchor; sed strips
# markdown bullet/bold and the leading label.
CURRENT_STEP=$(grep -iE "(current_step_file|current[ _]step|current[ _]phase)" "$SNAPSHOT_FILE" 2>/dev/null | head -1 | sed 's/^[^:]*://;s/^[-* ]*//;s/[-* ]*$//' || echo "")
LAST_GATE=$(grep -iE "(last_gate_passed|last[ _]gate)" "$SNAPSHOT_FILE" 2>/dev/null | head -1 | sed 's/^[^:]*://;s/^[-* ]*//;s/[-* ]*$//' || echo "")

REASON="Pipeline is active. You ended your turn without a tool call. This may be legitimate (presenting results mid-phase before the next action) or a stall.

CHECK BEFORE ACTING: Did you just complete a sub-skill and need to present its output before invoking the next one? If so, this is a FALSE POSITIVE — combine the presentation with the next tool call in your next response. Do NOT skip steps to avoid this hook.

If you genuinely have no next action (HARD_BLOCK, PVC, handoff, retro commentary): create the pause flag (touch _bmad-output/pipeline-paused.flag).

If you have a next action but emitted text first: pair the text with the tool call in your next response. Text + tool call = valid turn. Text alone = this hook fires.

IMPORTANT: This hook exists to prevent 'should I continue?' stalls (Rule 3). It does NOT mean 'skip the current step to produce a tool call faster.' Every numbered section in the current step file must be completed in full (Rule 4). If a section produces text output (party-mode results, failure classification, gate announcements), emit that text WITH the next section's tool call in the same response.

FIDELITY CHECK: Do NOT pattern-match on prior sprint execution. Re-read the current step file's numbered sections and execute each one literally. The pipeline is designed for fidelity, not throughput. Rushing through deploy-validate and retro — treating them as formalities because implementation feels 'done' — is the documented failure mode. Each section exists for a reason. Execute it."

if [ -n "$CURRENT_STEP" ]; then
  REASON="${REASON} Current step: ${CURRENT_STEP}."
fi
if [ -n "$LAST_GATE" ]; then
  REASON="${REASON} Last gate: ${LAST_GATE}."
fi

# -----------------------------------------------------------------------------
# Write updated state and log the block
# -----------------------------------------------------------------------------
echo "$NOW" > "$STATE_FILE"
echo "$COUNTER" >> "$STATE_FILE"

{
  echo "## ${TIMESTAMP} -- BLOCKED (rapid-fire ${COUNTER}/${MAX_RAPID_BLOCKS})"
  echo "- Session: ${SESSION_ID}"
  if [ -n "$CURRENT_STEP" ]; then
    echo "- Current step: ${CURRENT_STEP}"
  fi
  if [ -n "$LAST_GATE" ]; then
    echo "- Last gate: ${LAST_GATE}"
  fi
  echo "- Seconds since previous block: ${DELTA}"
  echo "- Reason returned to Claude: forced continuation (Rule 3)"
  echo ""
} >> "$LOG_FILE"

jq -n \
  --arg reason "$REASON" \
  '{
    decision: "block",
    reason: $reason,
    suppressOutput: true
  }'

exit 0