#!/bin/bash
#
# AI/DLC Pipeline Continuation Hook
#
# PURPOSE
# Enforces Rule 3 (Never stall the pipeline) when the pipeline is in
# autonomous mode. Respects user-initiated pauses via a flag file
# written by the UserPromptSubmit hook (ai-dlc-pause.sh).
#
# DECISION ORDER (first match wins)
# 1. pause flag exists               -> allow stop (user is driving)
# 2. no snapshot exists              -> allow stop (no active pipeline)
# 3. rapid-fire limit exceeded       -> allow stop (stall confirmed)
# 4. default                         -> block stop (force Rule 3 continue)
#
# RAPID-FIRE DETECTION (time-based, replaces stop_hook_active check)
# Tracks the timestamp of each block and a counter of consecutive
# rapid-fire blocks. If two blocks occur within 30 seconds of each
# other, they are counted as the same stall attempt. After 3 such
# rapid-fire blocks, the hook backs off and allows the stop.
#
# Why time-based instead of stop_hook_active? When the pipeline
# invokes multiple bmad skills in sequence (common in Discovery
# phase: brainstorming, advanced-elicit, adversarial-review),
# each skill's turn ends with a Stop event and Claude Code sets
# stop_hook_active=true on the next turn. The stop_hook_active
# signal cannot distinguish "genuine loop" from "legitimate
# multi-skill progression." A 30-second threshold cleanly
# separates the two: a real bmad skill takes far longer than
# 30 seconds, while a tight stall-and-retry happens in seconds.
#
# PAUSE CONTRACT
# The pause flag is created by:
#   1. ai-dlc-pause.sh on any user message during an active pipeline, OR
#   2. The lead itself when it has a legitimate intentional pause
#      (HARD_BLOCK awaiting operator decision per Rule 11(a), handoff
#      per Rule 2, gate failure, Production Validation Checkpoint).
# The lead interprets user intent and deletes the flag when the user
# wants to resume autonomous execution. This hook never creates or
# deletes the flag; it only reads it.
#
# DESIGN PRINCIPLE
# This hook prevents UNINTENTIONAL stalls. It does not prevent
# INTENTIONAL pauses. The lead has authority to pause when it knows
# it should pause (per AI/DLC rules). The flag file is the lead's
# mechanism to express that intent. The hook respects the flag
# regardless of who created it.
#
# OUTPUT
# - State: _bmad-output/pipeline-block-state.txt (2 lines:
#   last-block epoch timestamp, consecutive rapid-fire count)
# - Appends to: _bmad-output/pipeline-continuation-log.md
# - JSON to stdout on block: decision + reason
# - Exit 0 in all cases (block is in the JSON body)
#
# INSTALL
# 1. Place at .claude/hooks/ai-dlc-continue.sh
# 2. chmod +x .claude/hooks/ai-dlc-continue.sh
# 3. Add to .claude/settings.json hooks:
#      "Stop": [
#        {
#          "hooks": [{
#            "type": "command",
#            "command": "$CLAUDE_PROJECT_DIR/.claude/hooks/ai-dlc-continue.sh"
#          }]
#        }
#      ]
# 4. Restart Claude Code
# 5. Verify with /hooks

set -u

# -----------------------------------------------------------------------------
# Configuration
# -----------------------------------------------------------------------------
PROJECT_DIR="${CLAUDE_PROJECT_DIR:-.}"
SNAPSHOT_FILE="${PROJECT_DIR}/_bmad-output/pipeline-snapshot.md"
LOG_DIR="${PROJECT_DIR}/_bmad-output"
LOG_FILE="${LOG_DIR}/pipeline-continuation-log.md"
PAUSE_FLAG="${LOG_DIR}/pipeline-paused.flag"
STATE_FILE="${LOG_DIR}/pipeline-block-state.txt"

# Rapid-fire thresholds
RAPID_WINDOW_SECONDS=30
MAX_RAPID_BLOCKS=3

# -----------------------------------------------------------------------------
# Read hook input
# -----------------------------------------------------------------------------
INPUT=$(cat)
SESSION_ID=$(echo "$INPUT" | jq -r '.session_id // empty')
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
NOW=$(date +%s)

# -----------------------------------------------------------------------------
# Seed log header if needed
# -----------------------------------------------------------------------------
mkdir -p "$LOG_DIR"
if [ ! -s "$LOG_FILE" ]; then
  cat > "$LOG_FILE" <<'EOF'
# Pipeline Flow Log

Records pipeline-level events: user pauses, Rule 3 enforcement,
and rapid-fire stall detection. Generated by AI/DLC hook scripts.

Event types:

- `USER_PAUSE`: user sent a message; pipeline paused via flag file
- `BLOCKED`: Stop event blocked; Rule 3 enforcement forced continue
- `ALLOWED_BY_PAUSE`: Stop event allowed because pause flag exists
- `BACKOFF`: rapid-fire stop attempts detected; stall confirmed

Retro reviews this log to assess pipeline flow:

- High USER_PAUSE counts mean the user intervened often (normal for
  interactive sprints, concerning if unexpected)
- High BLOCKED counts mean Rule 3 enforcement is doing work; without
  the hook the pipeline would have stalled
- BACKOFF entries indicate the pipeline actually got stuck and the
  hook exhausted its retry budget. Investigate the transcript around
  each BACKOFF to find the upstream cause.

---

EOF
fi

# -----------------------------------------------------------------------------
# Check 1: Pause flag (user-initiated pause)
# -----------------------------------------------------------------------------
if [ -f "$PAUSE_FLAG" ]; then
  {
    echo "## ${TIMESTAMP} -- ALLOWED_BY_PAUSE"
    echo "- Session: ${SESSION_ID}"
    echo "- Pause flag present; stop allowed"
    echo ""
  } >> "$LOG_FILE"
  # Reset block state -- pause-resume cycle counts as progress
  rm -f "$STATE_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Check 2: No active pipeline
# -----------------------------------------------------------------------------
if [ ! -f "$SNAPSHOT_FILE" ]; then
  # No pipeline; no state to track
  rm -f "$STATE_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Read block state and compute rapid-fire status
# -----------------------------------------------------------------------------
LAST_TS=0
COUNTER=0

if [ -f "$STATE_FILE" ]; then
  LAST_TS=$(sed -n '1p' "$STATE_FILE" 2>/dev/null || echo "0")
  COUNTER=$(sed -n '2p' "$STATE_FILE" 2>/dev/null || echo "0")
  # Defensive: ensure numeric values
  [[ "$LAST_TS" =~ ^[0-9]+$ ]] || LAST_TS=0
  [[ "$COUNTER" =~ ^[0-9]+$ ]] || COUNTER=0
fi

DELTA=$((NOW - LAST_TS))

if [ "$DELTA" -lt "$RAPID_WINDOW_SECONDS" ]; then
  # Within rapid-fire window; same stall attempt
  COUNTER=$((COUNTER + 1))
else
  # Gap > window; progress happened (or first block)
  COUNTER=1
fi

# -----------------------------------------------------------------------------
# Check 3: Rapid-fire limit exceeded (genuine stall)
# -----------------------------------------------------------------------------
if [ "$COUNTER" -gt "$MAX_RAPID_BLOCKS" ]; then
  {
    echo "## ${TIMESTAMP} -- BACKOFF"
    echo "- Session: ${SESSION_ID}"
    echo "- ${MAX_RAPID_BLOCKS} consecutive rapid-fire blocks (within ${RAPID_WINDOW_SECONDS}s of each other); stall confirmed"
    echo "- Allowing stop. Investigate transcript for upstream cause."
    echo ""
  } >> "$LOG_FILE"
  rm -f "$STATE_FILE"
  exit 0
fi

# -----------------------------------------------------------------------------
# Default: Block the stop. Pipeline is active and autonomous.
# -----------------------------------------------------------------------------

# Extract current step and last gate from snapshot (best-effort).
# Snapshots may format as "current_step_file: <path>" or
# "- **current_step_file:** <path>". No line-start anchor; sed strips
# markdown bullet/bold and the leading label.
CURRENT_STEP=$(grep -iE "(current_step_file|current[ _]step|current[ _]phase)" "$SNAPSHOT_FILE" 2>/dev/null | head -1 | sed 's/^[^:]*://;s/^[-* ]*//;s/[-* ]*$//' || echo "")
LAST_GATE=$(grep -iE "(last_gate_passed|last[ _]gate)" "$SNAPSHOT_FILE" 2>/dev/null | head -1 | sed 's/^[^:]*://;s/^[-* ]*//;s/[-* ]*$//' || echo "")

REASON="Pipeline is active and in autonomous mode. You just ended your turn without invoking the next action. If you have a legitimate reason to pause (HARD_BLOCK awaiting operator decision per Rule 11(a), handoff per Rule 2, gate failure, Production Validation Checkpoint, or other intentional pause), create the pause flag before ending your turn: touch _bmad-output/pipeline-paused.flag. The hook will respect the flag on your next Stop event. If you do not have a legitimate pause reason, do not emit another text-only transition message — your next response MUST include the tool call or skill invocation that performs the pending transition. If you just completed a bmad skill, invoke the next bmad skill in the sequence defined by the current step file. If you just finished a step's required actions, execute the step file's next instruction. Per SKILL.md Rule 3, the pipeline cannot stall unintentionally."

if [ -n "$CURRENT_STEP" ]; then
  REASON="${REASON} Current step: ${CURRENT_STEP}."
fi
if [ -n "$LAST_GATE" ]; then
  REASON="${REASON} Last gate: ${LAST_GATE}."
fi

# -----------------------------------------------------------------------------
# Write updated state and log the block
# -----------------------------------------------------------------------------
echo "$NOW" > "$STATE_FILE"
echo "$COUNTER" >> "$STATE_FILE"

{
  echo "## ${TIMESTAMP} -- BLOCKED (rapid-fire ${COUNTER}/${MAX_RAPID_BLOCKS})"
  echo "- Session: ${SESSION_ID}"
  if [ -n "$CURRENT_STEP" ]; then
    echo "- Current step: ${CURRENT_STEP}"
  fi
  if [ -n "$LAST_GATE" ]; then
    echo "- Last gate: ${LAST_GATE}"
  fi
  echo "- Seconds since previous block: ${DELTA}"
  echo "- Reason returned to Claude: forced continuation (Rule 3)"
  echo ""
} >> "$LOG_FILE"

jq -n \
  --arg reason "$REASON" \
  '{
    decision: "block",
    reason: $reason
  }'

exit 0