#!/usr/bin/env bash
# layer-entry-unreadable — prove that "I could not READ this entry" and "this entry has no
# such key" are two facts and not one. PC-S307.
#
# Usage: run.sh [path-to-validate-layer-entries.sh]
# Exit:  0 = every assertion holds, 1 = something regressed, 2 = the fixture cannot express
#        its own defect (FIXTURE BROKEN — see the precondition below).
#
# `fm()` reads one frontmatter scalar with one `awk` per file per key, and awk prints
# nothing in BOTH of these states:
#
#   ok.md         stdout=[x] rc=0        keyless.md    stdout=[] rc=0
#   unreadable.md stdout=[] rc=2         missing.md    stdout=[] rc=2
#
# Every caller read the value through `$( )` and threw the status away, so a read failure
# was reported as a missing key — a claim about a file's CONTENT made by a run that never
# saw the content. Measured on a consumer inside a freshly created `git worktree`: 20 false
# ERRORs against two demonstrably well-formed files, alongside `awk: can't open file` on
# stderr.
#
# BOTH DIRECTIONS, OR NEITHER. Parts 1 and 2 run the SAME file, generated by the same seed
# helper, into the same tree twice: once chmod 000, once readable with the receipt line
# removed. A validator that refuses everything it is handed produces Part 1's verdict and
# Part 2's verdict identically; only one that discriminates produces exit 2 with no finding
# for the first and exit 1 with an E17 for the second.
#
# WHY THE MUTANTS NEED SEVEN TREES AND NOT ONE. The eight guarded call sites read in a
# fixed order over two populations, and an earlier guard pre-empts every later one on the
# same file. Measured here, every guard deleted singly against every tree:
#
#   site 1  census loop, `conforms_to`   ext + ovr   first reader of everything
#   site 2  overrides loop, `shadows`    ovr         first reader when LC_CV is ''
#   site 3  live-layer loop, `hooks`     ext         first reader when LC_CV is ''
#   site 4  extensions loop, `kind`      ext         always behind site 3
#   site 5  extensions loop, `extends`   ext         behind 4; permissive
#   site 6  extensions loop, `position`  ext         behind 5; permissive
#   site 7  extensions loop, `gate_types` ext        behind 6; permissive
#   site 8  reference loop, `shadows`    ext + ovr   LAST; acquittal, not permissive
#
# Three consequences the arms below are shaped by. Sites 2 onward are only observable where
# the census loop does not run -- `if [ -n "$LC_CV" ]` -- which is why two trees carry an
# unreadable contract_version. Site 8 reads BOTH populations last, so it is now the backstop
# that aborts any permanently unreadable entry: no earlier guard owns the exit code any
# more, and what each one still buys is the false findings printed BEFORE the abort. And
# site 4 is observable only once site 3 is gone -- DELETING SITE 4's GUARD ALONE CHANGES NO
# OUTPUT ON ANY OF THE SEVEN TREES, re-measured, against a control showing the same
# comparison does find a difference for site 3. m4 therefore reverts both layers over that
# population, per the rule that a partial revert of a layered fix proves the layer it left
# in place and comes out green.
#
# SITES 5-8 CANNOT BE REACHED BY chmod 000 AT ALL, and Part 7 explains what replaces it.
#
# Every mutant is a COPY guarded by `cmp -s` and `bash -n`, there is an UNMUTATED control
# from the same directory with a positive conjunct, and each mutant asserts a measured
# POSITIVE outcome rather than the absence of a message.
set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"

pick() { for c in "$@"; do [ -n "$c" ] && [ -f "$c" ] && { printf '%s' "$c"; return; }; done; }
LINTER="$(pick "${1:-}" "$HERE/../../../scripts/ai-dlc/validate-layer-entries.sh" \
                        "$HERE/../../scripts/validate-layer-entries.sh" \
                        "$HERE/../../../core/scripts/validate-layer-entries.sh")"
[ -n "$LINTER" ] || { echo "FIXTURE BROKEN: cannot locate validate-layer-entries.sh" >&2; exit 2; }
# PRINTED, because a mutant applied to a file the run never loads leaves every arm green and
# `cmp -s` cannot see it -- the mutation applied cleanly, to the wrong copy.
echo "layer-entry-unreadable: subject = $LINTER"

ROOT="$(bash "$HERE/seed.sh")"
[ -n "$ROOT" ] && [ -d "$ROOT" ] || { echo "FIXTURE BROKEN: seed produced no sandbox" >&2; exit 2; }
TMP="$(mktemp -d "${TMPDIR:-/tmp}/layer-entry-unreadable-mut.XXXXXX")"
# CHMOD BACK BEFORE THE rm. A 000 file inside a directory `rm -rf` must unlink is fine on
# this platform and is not fine everywhere, and a fixture that leaves its sandbox behind on
# some machines is a fixture that fails somewhere nobody is looking.
cleanup() { chmod -R u+rwX "$ROOT" 2>/dev/null; rm -rf "$ROOT" "$TMP"; }
trap cleanup EXIT

CONS="$ROOT/consumer"; UNR="$ROOT/unreadable"; KEY="$ROOT/keyless"
OVRT="$ROOT/nolc-ovr"; EXTT="$ROOT/nolc-ext"

# --------------------------------------------------------------------------------------
# PRECONDITION — a fixture whose tree cannot EXPRESS the defect proves nothing
# --------------------------------------------------------------------------------------
# `chmod 000` does not make a file unreadable for root, and it does not make one unreadable
# on a filesystem mounted without permissions. Under either, every arm below runs against a
# perfectly readable entry and reports PASS having asserted nothing at all. This is the one
# state the fixture must call BROKEN rather than clean.
for _s in "$UNR/.claude/skills/ai-dlc/extensions/subject.md" \
          "$OVRT/.claude/skills/ai-dlc/overrides/subject-ovr.md" \
          "$EXTT/.claude/skills/ai-dlc/extensions/subject-ext.md"; do
  [ -f "$_s" ] || { echo "FIXTURE BROKEN: seed did not write $_s" >&2; exit 2; }
  if cat "$_s" >/dev/null 2>&1; then
    echo "FIXTURE BROKEN: $_s is STILL READABLE after chmod 000 — this fixture's subject is" >&2
    echo "  a read failure, and on this machine it cannot produce one (running as root, or a" >&2
    echo "  filesystem with no permission bits). Every assertion below would pass vacuously." >&2
    exit 2
  fi
done
# And the CONTROL for that loop: a file seeded the same way, deliberately left readable. A
# `cat` that fails for some unrelated reason -- a wrong path, a dead sandbox -- would satisfy
# the check above on every file and report the same clean line.
cat "$CONS/.claude/skills/ai-dlc/extensions/current-a.md" >/dev/null 2>&1 || {
  echo "FIXTURE BROKEN: a deliberately READABLE seeded entry could not be read either, so the" >&2
  echo "  unreadability check above proves nothing about permissions." >&2; exit 2; }

ASSERTIONS=0
fails=0
ok()  { ASSERTIONS=$((ASSERTIONS+1)); printf '  ok   %s\n' "$1"; }
bad() { ASSERTIONS=$((ASSERTIONS+1)); fails=$((fails+1)); printf '  FAIL %s\n' "$1"; }
say() { if [ "$1" = 1 ]; then ok "$2"; else bad "$2"; fi; }

# NO run() HELPER, deliberately. `OUT="$(run ...)"` evaluates the helper in a SUBSHELL, so an
# rc it assigns to a global is discarded and every exit-code assertion below would read a
# stale 0. Each call site captures `$?` on the same line as its own command substitution.

# footer_field <output> <name> -- value of name= on the LAYER_CONFORMANCE line.
# HERE-STRING, not a pipe: the awk program `exit`s at the first match, so under pipefail a
# large enough value would make the writer die on EPIPE and the field read as absent.
footer_field() {
  awk -v k="$2" '
    /^LAYER_CONFORMANCE / { for (i=2; i<=NF; i++) { split($i, p, "="); if (p[1] == k) { print p[2]; exit } } }' <<<"$1"
}
# fatal_for <output> <path-suffix> -- rc 0 when a FATAL line names that file.
# Two greps over a captured string rather than a pipeline, and the trailing quote is part of
# the needle so `subject.md'` cannot be satisfied by `subject-ext.md'`.
fatal_for() {
  local _f; _f="$(grep -F 'could not READ' <<<"$1")"
  [ -n "$_f" ] && grep -Fq "$2'" <<<"$_f"
}
# errs_naming <output> <path-suffix> -- how many ERROR lines name that file
errs_naming() {
  awk -v p="$2" 'index($0,"ERROR")==1 && index($0,p)>0 { n++ } END { print n+0 }' <<<"$1"
}
has() { grep -Fq "$2" <<<"$1"; }

echo "layer-entry-unreadable:"

# --------------------------------------------------------------------------------------
# Part 1 — an entry that cannot be READ produces a refusal and NO finding about it
# --------------------------------------------------------------------------------------
UNR_OUT="$(bash "$LINTER" "$UNR" 2>&1)"; UNR_RC=$?
say "$([ "$UNR_RC" -eq 2 ] && echo 1 || echo 0)" \
  "an unreadable entry exits 2 — the 'could not run' code, never 0 and never a 1 that reads as a verdict"
say "$(fatal_for "$UNR_OUT" 'extensions/subject.md' && echo 1 || echo 0)" \
  "the FATAL names the file it could not read, so the operator is told WHICH entry"
say "$([ "$(errs_naming "$UNR_OUT" 'extensions/subject.md')" -eq 0 ] && echo 1 || echo 0)" \
  "ZERO ERROR lines name that file — no claim about content this run never saw"

# --------------------------------------------------------------------------------------
# Part 2 — the discriminating twin: same file, readable, key genuinely absent
# --------------------------------------------------------------------------------------
# A validator that refused every entry handed to it would satisfy Part 1 exactly. This is
# the input that separates the two, and it differs from Part 1's by one chmod and one line.
KEY_OUT="$(bash "$LINTER" "$KEY" 2>&1)"; KEY_RC=$?
say "$([ "$KEY_RC" -eq 1 ] && echo 1 || echo 0)" \
  "a genuinely keyless entry exits 1 — a finding, not a refusal"
say "$(has "$KEY_OUT" "extensions/subject.md: missing 'conforms_to:'" && echo 1 || echo 0)" \
  "and it still takes its ordinary E17 missing-key ERROR, named"
say "$(! grep -Fq 'could not READ' <<<"$KEY_OUT" && echo 1 || echo 0)" \
  "the keyless twin draws no FATAL, so the refusal is keyed on the READ and not on the key"

# --------------------------------------------------------------------------------------
# Part 3 — the baseline this all sits on
# --------------------------------------------------------------------------------------
CONS_OUT="$(bash "$LINTER" "$CONS" 2>&1)"; CONS_RC=$?
say "$([ "$CONS_RC" -eq 0 ] && [ "$(footer_field "$CONS_OUT" entries)" = 2 ] \
       && [ "$(footer_field "$CONS_OUT" errors)" = 0 ] && echo 1 || echo 0)" \
  "a readable, well-formed consumer exits 0 with the footer counting both its entries"

# --------------------------------------------------------------------------------------
# Part 4 — the two trees the later guards are the first reader on
# --------------------------------------------------------------------------------------
# `contract_version` is made unreadable rather than the contract deleted: the validator
# ERRORs, sets LC_CV empty and CARRIES ON, which is the reachable state in which the census
# loop is skipped. These two rows are the unmutated baseline m2, m3 and m4 move.
OVR_OUT="$(bash "$LINTER" "$OVRT" 2>&1)"; OVR_RC=$?
say "$([ "$OVR_RC" -eq 2 ] && fatal_for "$OVR_OUT" 'overrides/subject-ovr.md' \
       && [ "$(errs_naming "$OVR_OUT" 'overrides/subject-ovr.md')" -eq 0 ] && echo 1 || echo 0)" \
  "an unreadable OVERRIDE refuses too, with no E1 about frontmatter nobody read"
EXT_OUT="$(bash "$LINTER" "$EXTT" 2>&1)"; EXT_RC=$?
say "$([ "$EXT_RC" -eq 2 ] && fatal_for "$EXT_OUT" 'extensions/subject-ext.md' \
       && ! has "$EXT_OUT" 'EMPTY resolvability set' \
       && [ "$(errs_naming "$EXT_OUT" 'extensions/subject-ext.md')" -eq 0 ] && echo 1 || echo 0)" \
  "an unreadable EXTENSION refuses before the resolvability set is judged, so E16 makes no claim"

# --------------------------------------------------------------------------------------
# Part 5 — cwd invariance, asserted rather than assumed
# --------------------------------------------------------------------------------------
# A fixture green only from the repo root may be asserting nothing, and this one resolves
# both its subject and its seed from `$HERE`. Re-run the same subject on the same tree from
# `/` and require the identical verdict; a subject that resolved anything from the process
# working directory answers differently here.
CWD_OUT="$(cd / && bash "$LINTER" "$UNR" 2>&1)"; CWD_RC=$?
say "$([ "$CWD_RC" -eq "$UNR_RC" ] && fatal_for "$CWD_OUT" 'extensions/subject.md' && echo 1 || echo 0)" \
  "the same verdict and the same FATAL when the subject is invoked from / — cwd-invariant"

# --------------------------------------------------------------------------------------
# Part 6 — mutants
# --------------------------------------------------------------------------------------
mk() { # mk <name> <command...> -- build a mutant COPY, guarded by cmp -s and bash -n
  local name="$1"; shift
  if ! "$@" < "$LINTER" > "$TMP/$name.sh"; then
    bad "MUTANT $name: the mutating command itself failed, so nothing below is a kill"
    return 1
  fi
  if cmp -s "$LINTER" "$TMP/$name.sh"; then
    bad "MUTANT $name: the mutation matched NOTHING — an unchanged copy scores every kill it is offered"
    return 1
  fi
  if ! bash -n "$TMP/$name.sh" 2>/dev/null; then
    bad "MUTANT $name: the mutant does not parse, so its silence is a syntax error and not a kill"
    return 1
  fi
  return 0
}

# UNMUTATED CONTROL from the same directory as every mutant. A copy that dies for an
# unrelated reason emits nothing, and "no output" would otherwise score as a kill. It
# carries POSITIVE conjuncts -- a baseline row that must be THERE, and a FATAL that must be
# THERE -- because rc=0-with-nothing-reported is exactly what a subject replaced by `exit 0`
# also looks like.
cp "$LINTER" "$TMP/control.sh"
CTL_C_OUT="$(bash "$TMP/control.sh" "$CONS" 2>&1)"; CTL_C_RC=$?
CTL_U_OUT="$(bash "$TMP/control.sh" "$UNR" 2>&1)"; CTL_U_RC=$?
say "$([ "$CTL_C_RC" -eq 0 ] && [ "$(footer_field "$CTL_C_OUT" entries)" = 2 ] \
       && [ "$CTL_U_RC" -eq 2 ] && fatal_for "$CTL_U_OUT" 'extensions/subject.md' && echo 1 || echo 0)" \
  "CONTROL: an unmutated copy still counts 2 entries on the clean tree and still FATALs on the unreadable one"

# --- m1: the census loop's guard — the site that READS FIRST -------------------------------
# Without it the run still refuses, at a later site, having already printed one collapsed
# finding. That single ERROR line is the whole of PC-S307 as it was reported.
if mk m1 sed 's@^    ct="$(fm "$f" conforms_to)" || entry_unreadable "$f"$@    ct="$(fm "$f" conforms_to)"@'; then
  M1_OUT="$(bash "$TMP/m1.sh" "$UNR" 2>&1)"; M1_RC=$?
  say "$(has "$M1_OUT" "extensions/subject.md: missing 'conforms_to:'" && echo 1 || echo 0)" \
    "MUTANT m1 killed: the census loop invents a missing-key ERROR about a file awk could not open"
  # ATTRIBUTION. m1 must move exactly one cell. The run still exits 2 from a later guard, so
  # the kill above is the ERROR line and not a collapse of the whole guard set.
  say "$([ "$M1_RC" -eq 2 ] && fatal_for "$M1_OUT" 'extensions/subject.md' && echo 1 || echo 0)" \
    "MUTANT m1 leaves the later guards alive — it costs a false finding, not the refusal"
fi

# --- m2: the overrides guard ---------------------------------------------------------------
# Anchored on `shadows=`, which is what SEPARATES this site from the three others: all four
# open with the same `"$(fm ` and a needle keyed on that would edit every one of them.
if mk m2 sed 's@^  shadows="$(fm "$f" shadows)" || entry_unreadable "$f"$@  shadows="$(fm "$f" shadows)"@'; then
  M2_OUT="$(bash "$TMP/m2.sh" "$OVRT" 2>&1)"; M2_RC=$?
  # THE RUN STILL EXITS 2, and it did not before the second round of guards landed. The
  # reference-resolution loop reads `shadows:` off every entry in BOTH populations, so it is
  # now the last backstop for any unreadable file and no single earlier guard owns the abort
  # any more. What this guard alone still buys is the three false findings below never being
  # printed — which is PC-S307 as the consumer actually reported it.
  say "$([ "$M2_RC" -eq 2 ] && has "$M2_OUT" "overrides/subject-ovr.md: missing 'shadows:'" && echo 1 || echo 0)" \
    "MUTANT m2 killed: the overrides pass reports frontmatter it never read, ahead of the abort a later guard still makes"
fi

# --- m3: the live-layer guard — the SILENT direction ---------------------------------------
# `[ -n "$_lh" ] || continue` sits one line below it, so an unreadable entry reads as
# "declares no hook" and leaves the resolvability set with no finding at all. The observable
# is POSITIVE and not the absence of a message: E16 reports the set it then built as EMPTY,
# a completeness claim derived from a file nobody could open. The seed gives this tree
# exactly ONE extension so that dropping it empties the set and E16 can speak.
if mk m3 sed 's@^  _lh="$(fm "$_lf" hooks)" || entry_unreadable "$_lf"$@  _lh="$(fm "$_lf" hooks)"@'; then
  M3_OUT="$(bash "$TMP/m3.sh" "$EXTT" 2>&1)"; M3_RC=$?
  say "$(has "$M3_OUT" 'built an EMPTY resolvability set from the 1 layer entr(y/ies) present' && echo 1 || echo 0)" \
    "MUTANT m3 killed: the entry drops out of the resolvability set and E16 judges the hole it left"
  # ATTRIBUTION, and it is also the measurement that shapes m4: the run STILL exits 2, from
  # the extensions guard one loop later. So m3's cost is exactly the silent drop.
  say "$([ "$M3_RC" -eq 2 ] && fatal_for "$M3_OUT" 'extensions/subject-ext.md' && echo 1 || echo 0)" \
    "MUTANT m3 still refuses at the next guard — its cost is the silent drop, nothing else"
fi

# --- m4: the extensions guard, which is the LAYER UNDER m3 ---------------------------------
# BOTH LAYERS COME OUT, and that is not a shortcut. Sites 3 and 4 read the same population in
# a fixed order, so site 3 pre-empts site 4 on every file: deleting site 4's guard alone
# changes no byte of output on any of the five seeded trees, measured. A single-layer revert
# would produce a mutant that proves the layer it left in place and comes out green.
#
# THE LABEL BELOW DELIBERATELY CARRIES NO ERROR-CODE TOKEN, and reintroducing one turns the
# push red. I65 reads a code named anywhere in a fixture that drives its enforcer as a claim
# that the fixture PROVES the clause owning that code, and demands the clause name it back.
# This arm shows the code firing on an UNREADABLE entry with the guards removed — which is
# the spurious emission this release exists to stop, not a proof that a genuinely keyless
# extension is caught. Claiming it would close a counted gap with a false attribution. The
# assertion greps the message text, which carries no code, so nothing is weakened by this.
if mk m4 sed -e 's@^  _lh="$(fm "$_lf" hooks)" || entry_unreadable "$_lf"$@  _lh="$(fm "$_lf" hooks)"@' \
             -e 's@^  kind="$(fm "$f" kind)" || entry_unreadable "$f"$@  kind="$(fm "$f" kind)"@'; then
  M4_OUT="$(bash "$TMP/m4.sh" "$EXTT" 2>&1)"; M4_RC=$?
  # The occurrence count proves the SECOND expression matched too. `cmp -s` is satisfied by
  # either one of them, so without this m4 could be m3 wearing a longer sed. RELATIVE to the
  # subject and never a literal: a fixed `-eq 3` also fails when some OTHER site is missing
  # from the subject, which is this arm reporting a defect that is not its own.
  M4_LEFT="$(grep -c 'entry_unreadable' "$TMP/m4.sh")"
  M4_BASE="$(grep -c 'entry_unreadable' "$LINTER")"
  say "$([ "$M4_RC" -eq 2 ] && [ "$M4_LEFT" -eq $((M4_BASE - 2)) ] \
         && has "$M4_OUT" "extensions/subject-ext.md: missing 'kind:'" && echo 1 || echo 0)" \
    "MUTANT m4 killed: with both extension-side guards gone the run reports missing-key findings about frontmatter nobody read"
fi

# --------------------------------------------------------------------------------------
# Part 7 — the reads whose EMPTY value is PERMISSIVE
# --------------------------------------------------------------------------------------
# The first four guards all sit on reads whose empty value MANUFACTURES a finding, so a
# failure there is loud and wrong. These four are the opposite class: every arm consuming
# them is gated on the value being non-empty, so an empty read reads as "key absent" and
# absent is the CONFORMING answer. A read failure does not add a finding, it DELETES one —
# and the count in the footer still looks plausible, which is why the existing arms (exit 2,
# zero ERRORs naming the file) cannot catch it. What catches it is asserting the specific
# rows are THERE readable and that the run REFUSES sealed.
#
# THESE SITES CANNOT BE REACHED BY chmod 000. Every earlier guard reads the same file first
# and refuses, so a permanently unreadable entry never gets here. The failure these guards
# exist for is a read that fails PART WAY THROUGH a run — the git-worktree race the filing
# names — so the fixture reproduces that directly: a copy of the subject whose `fm()`
# returns for one file and one key set exactly what `awk` returns when it cannot open a
# file. That pair is not invented; C2 below measures it off the shipped `fm()` itself.
PERM="$ROOT/permissive"; CITE="$ROOT/citation"
PERM_SUBJ="$PERM/.claude/skills/ai-dlc/extensions/role-entry.md"
CITE_SUBJ="$CITE/.claude/skills/ai-dlc/extensions/cite-ext.md"

# nrows <output> <code> <path-suffix> -- how many finding rows carry that code AND name that file
nrows() {
  awk -v c="$2" -v p="$3" '$1 ~ /^(ERROR|WARN)$/ && $2 == c && index($0, p) > 0 { n++ } END { print n+0 }' <<<"$1"
}
# sr <script> <seal-keys> <tree> <seal-file> -- run, leaving SR_OUT/SR_RC. NOT via `X="$(sr …)"`,
# which would evaluate the whole helper in a subshell and discard the rc it assigns.
sr() { SR_OUT="$(FX_SEAL_FILE="$4" FX_SEAL_KEYS="$2" bash "$1" "$3" 2>&1)"; SR_RC=$?; }

# --- C1: the tree can EXPRESS the defect. Without this every arm below is vacuous. --------
# The first probe of this defect seeded no `steps/retro.md`, so the entry took an E5 and
# `continue`d before the arms under test ever ran — a clean-looking zero that proved nothing.
sr "$LINTER" '' "$PERM" ''
say "$([ "$SR_RC" -eq 1 ] \
       && [ "$(nrows "$SR_OUT" E11 'extensions/role-entry.md')" -eq 1 ] \
       && [ "$(nrows "$SR_OUT" E12 'extensions/role-entry.md')" -eq 1 ] \
       && [ "$(nrows "$SR_OUT" E13 'extensions/role-entry.md')" -eq 1 ] \
       && [ "$(nrows "$SR_OUT" E14 'extensions/role-entry.md')" -eq 1 ] && echo 1 || echo 0)" \
  "READABLE, the role entry draws all four permissive-arm findings — the tree reaches the sites"
PERM_ERRS="$(footer_field "$SR_OUT" errors)"

# --- C2: the seal is FAITHFUL, measured off the shipped fm() and in BOTH directions -------
# A hand-written stand-in is a second implementation whose bugs nobody finds, so the pair the
# seal returns is taken from the real function against real files. Both directions, because a
# stand-in that failed on everything would satisfy the first half alone. (Measured while
# building this: `awk 'END{}'` on a 000 file exits 0, not 2 — a program with no input-reading
# rule never opens its operand. The shipped grammar is the only faithful probe.)
FM_BODY="$(sed -n '/^fm() {/,/^}/p' "$LINTER")"
{ printf '%s\n' "$FM_BODY"; printf 'fm "$1" "$2"\n'; } > "$TMP/fmprobe.sh"
FM_U_OUT="$(bash "$TMP/fmprobe.sh" "$UNR/.claude/skills/ai-dlc/extensions/subject.md" conforms_to 2>/dev/null)"; FM_U_RC=$?
FM_K_OUT="$(bash "$TMP/fmprobe.sh" "$KEY/.claude/skills/ai-dlc/extensions/subject.md" conforms_to 2>/dev/null)"; FM_K_RC=$?
say "$([ -n "$FM_BODY" ] && [ -z "$FM_U_OUT" ] && [ "$FM_U_RC" -ne 0 ] \
       && [ -z "$FM_K_OUT" ] && [ "$FM_K_RC" -eq 0 ] && echo 1 || echo 0)" \
  "the shipped fm() answers empty/non-zero on an unreadable file and empty/ZERO on a keyless one — the pair the seal imitates"

# --- build the sealed copy ----------------------------------------------------------------
mkseal() { # mkseal <in> <out> -- fm() returns empty with rc 2 for one file and a named key set
  awk '
    /^fm\(\) \{/ && !d {
      print
      print "  if [ -n \"${FX_SEAL_FILE:-}\" ] && [ \"$1\" = \"$FX_SEAL_FILE\" ]; then"
      print "    case \" ${FX_SEAL_KEYS:-} \" in *\" $2 \"*) return 2 ;; esac"
      print "  fi"
      d = 1; next
    }
    { print }' < "$1" > "$2"
}
mkseal "$LINTER" "$TMP/sealed.sh"
SEAL_OK=0
if cmp -s "$LINTER" "$TMP/sealed.sh"; then
  bad "SEAL: the injection matched nothing, so every arm below would run the shipped subject"
elif ! bash -n "$TMP/sealed.sh" 2>/dev/null; then
  bad "SEAL: the sealed copy does not parse, so its silence would be a syntax error"
else
  # --- C3: and it is INERT until armed. -------------------------------------------------
  # Compared on rc and the ERROR rows rather than on whole output: a copy resolves
  # `artifact-path-config.sh` from beside ITSELF, so W11's wording differs in every copy in
  # this directory. That difference reaches no arm, and asserting on it would fail here for
  # a reason that has nothing to do with the seal.
  sr "$TMP/sealed.sh" '' "$PERM" ''
  say "$([ "$SR_RC" -eq 1 ] && [ "$(footer_field "$SR_OUT" errors)" = "$PERM_ERRS" ] \
         && [ "$(nrows "$SR_OUT" E11 'extensions/role-entry.md')" -eq 1 ] \
         && [ "$(nrows "$SR_OUT" E14 'extensions/role-entry.md')" -eq 1 ] && echo 1 || echo 0)" \
    "SEAL CONTROL: unarmed, the sealed copy reproduces the shipped verdict and error count"
  SEAL_OK=1
fi

if [ "$SEAL_OK" = 1 ]; then
  # --- C4-C6: armed, the shipped guards REFUSE at each permissive site -------------------
  # Later sites legitimately emit the findings the earlier arms already produced before the
  # abort, so unlike Part 1 these do NOT assert zero ERRORs naming the file. What they assert
  # is the refusal: no verdict is issued over a file this run could not finish reading.
  for _k in extends position gate_types; do
    sr "$TMP/sealed.sh" "$_k" "$PERM" "$PERM_SUBJ"
    say "$([ "$SR_RC" -eq 2 ] && fatal_for "$SR_OUT" 'extensions/role-entry.md' \
           && [ -z "$(footer_field "$SR_OUT" errors)" ] && echo 1 || echo 0)" \
      "a mid-run read failure on '$_k' REFUSES — exit 2, named, and no footer passing judgement"
  done

  # --- C7/C8: the acquittal site, which is the odd one of the eight ---------------------
  sr "$LINTER" '' "$CITE" ''
  say "$([ "$SR_RC" -eq 0 ] && [ "$(nrows "$SR_OUT" W12 'extensions/cite-ext.md')" -eq 0 ] && echo 1 || echo 0)" \
    "READABLE, the cited entry is ACQUITTED by its own shadows anchor — no W12, exit 0"
  sr "$TMP/sealed.sh" shadows "$CITE" "$CITE_SUBJ"
  say "$([ "$SR_RC" -eq 2 ] && fatal_for "$SR_OUT" 'extensions/cite-ext.md' && echo 1 || echo 0)" \
    "and a mid-run read failure on 'shadows' REFUSES rather than judging the citation"

  # --------------------------------------------------------------------------------------
  # Part 8 — mutants for the four permissive guards, built from the SEALED copy
  # --------------------------------------------------------------------------------------
  mkfrom() { # mkfrom <base> <name> <command...>
    local base="$1" name="$2"; shift 2
    if ! "$@" < "$base" > "$TMP/$name.sh"; then
      bad "MUTANT $name: the mutating command itself failed, so nothing below is a kill"; return 1
    fi
    if cmp -s "$base" "$TMP/$name.sh"; then
      bad "MUTANT $name: the mutation matched NOTHING — an unchanged copy scores every kill it is offered"; return 1
    fi
    if ! bash -n "$TMP/$name.sh" 2>/dev/null; then
      bad "MUTANT $name: the mutant does not parse, so its silence is a syntax error and not a kill"; return 1
    fi
    return 0
  }

  # --- m5: `extends` -- E11 is the row it alone can lose -------------------------------
  # POSITIVE CONJUNCTS CARRY THIS ARM. "E11 is gone" alone is satisfied by a subject that
  # emits nothing at all, so the other three rows and a full footer must still be THERE:
  # that combination — a plausible report, three findings, one silently missing — is the
  # exact shape of the defect and nothing else produces it.
  if mkfrom "$TMP/sealed.sh" m5 sed 's@^  _ext_raw="$(fm "$f" extends)"     || entry_unreadable "$f"$@  _ext_raw="$(fm "$f" extends)"@'; then
    sr "$TMP/m5.sh" extends "$PERM" "$PERM_SUBJ"
    say "$([ "$SR_RC" -eq 1 ] && [ "$(nrows "$SR_OUT" E11 'extensions/role-entry.md')" -eq 0 ] \
           && [ "$(nrows "$SR_OUT" E12 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(nrows "$SR_OUT" E13 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(nrows "$SR_OUT" E14 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(footer_field "$SR_OUT" errors)" = "$((PERM_ERRS - 1))" ] && echo 1 || echo 0)" \
      "MUTANT m5 killed: E11 vanishes while the other three rows and a full footer stay — a finding DELETED, not raised"
  fi

  # --- m6: `position` -- it owns TWO rows, and both must go ----------------------------
  if mkfrom "$TMP/sealed.sh" m6 sed 's@^  _pos_raw="$(fm "$f" position)"    || entry_unreadable "$f"$@  _pos_raw="$(fm "$f" position)"@'; then
    sr "$TMP/m6.sh" position "$PERM" "$PERM_SUBJ"
    say "$([ "$SR_RC" -eq 1 ] && [ "$(nrows "$SR_OUT" E12 'extensions/role-entry.md')" -eq 0 ] \
           && [ "$(nrows "$SR_OUT" E13 'extensions/role-entry.md')" -eq 0 ] \
           && [ "$(nrows "$SR_OUT" E11 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(nrows "$SR_OUT" E14 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(footer_field "$SR_OUT" errors)" = "$((PERM_ERRS - 2))" ] && echo 1 || echo 0)" \
      "MUTANT m6 killed: BOTH rows this key feeds vanish, and the two it does not feed remain"
  fi

  # --- m7: `gate_types` ------------------------------------------------------------------
  if mkfrom "$TMP/sealed.sh" m7 sed 's@^  _gt_raw="$(fm "$f" gate_types)"   || entry_unreadable "$f"$@  _gt_raw="$(fm "$f" gate_types)"@'; then
    sr "$TMP/m7.sh" gate_types "$PERM" "$PERM_SUBJ"
    say "$([ "$SR_RC" -eq 1 ] && [ "$(nrows "$SR_OUT" E14 'extensions/role-entry.md')" -eq 0 ] \
           && [ "$(nrows "$SR_OUT" E11 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(nrows "$SR_OUT" E12 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(nrows "$SR_OUT" E13 'extensions/role-entry.md')" -eq 1 ] \
           && [ "$(footer_field "$SR_OUT" errors)" = "$((PERM_ERRS - 1))" ] && echo 1 || echo 0)" \
      "MUTANT m7 killed: E14 vanishes alone, so the guard is attributable to its own read"
  fi

  # --- m8: the acquittal read, and it runs the OTHER WAY --------------------------------
  # MEASURED, AND IT IS NOT THE CLASS THE OTHER THREE ARE. Its only consumer acquits on a
  # NON-empty value, so an empty read withdraws the acquittal: the failure ADDS a W12 about a
  # citation the entry had already disambiguated. Same guard, opposite harm — and the arm has
  # to assert the row APPEARS, because asserting a row went missing would pass here forever.
  #
  # It is also the worst-instrumented of the eight: `shadow_parts … 2>/dev/null` on the very
  # next line swallows awk's own "can't open file", so before the guard this failure left no
  # trace anywhere — not a finding, not a message, not an exit code.
  if mkfrom "$TMP/sealed.sh" m8 sed 's@^  _sh_raw="$(fm "$f" shadows)" || entry_unreadable "$f"$@  _sh_raw="$(fm "$f" shadows)"@'; then
    sr "$TMP/m8.sh" shadows "$CITE" "$CITE_SUBJ"
    say "$([ "$(nrows "$SR_OUT" W12 'extensions/cite-ext.md')" -eq 1 ] && [ "$SR_RC" -eq 0 ] && echo 1 || echo 0)" \
      "MUTANT m8 killed: the lost acquittal RAISES a W12 the readable run does not — this site adds a finding, it does not delete one"
  fi

  # --- m9: re-nest the read inside unquote, which is how the status gets swallowed -------
  # `$(unquote "$(fm …)")` reports UNQUOTE's status and never fm's, so the guard survives in
  # the source and watches the wrong call. This is the `$(fm … | awk …)` hazard from the
  # extensions loop wearing different brackets, and it is why the raw read is on its own line.
  if mkfrom "$TMP/sealed.sh" m9 sed \
      -e 's@^  _ext_raw="$(fm "$f" extends)"     || entry_unreadable "$f"$@  _ext_raw="$(unquote "$(fm "$f" extends)")" || entry_unreadable "$f"@' \
      -e 's@^  extends="$(unquote "$_ext_raw")"$@  extends="$_ext_raw"@'; then
    M9_LEFT="$(grep -c 'entry_unreadable' "$TMP/m9.sh")"
    M9_BASE="$(grep -c 'entry_unreadable' "$TMP/sealed.sh")"
    sr "$TMP/m9.sh" extends "$PERM" "$PERM_SUBJ"
    say "$([ "$SR_RC" -eq 1 ] && [ "$M9_LEFT" -eq "$M9_BASE" ] \
           && [ "$(nrows "$SR_OUT" E11 'extensions/role-entry.md')" -eq 0 ] \
           && [ "$(nrows "$SR_OUT" E14 'extensions/role-entry.md')" -eq 1 ] && echo 1 || echo 0)" \
      "MUTANT m9 killed: with the read nested back inside unquote the guard is still THERE, still spelled right, and never fires"
fi
fi

# --------------------------------------------------------------------------------------
# ASSERTION FLOOR. An arm that never executes -- a helper that returned early, a mutant whose
# `mk` bailed -- leaves a green report that reads exactly like a passing one.
# --------------------------------------------------------------------------------------
EXPECTED_ASSERTIONS=30
echo
if [ "$ASSERTIONS" -ne "$EXPECTED_ASSERTIONS" ]; then
  printf 'layer-entry-unreadable: FAIL — %d assertions ran, %d expected. An arm did not execute.\n' \
    "$ASSERTIONS" "$EXPECTED_ASSERTIONS"
  exit 1
fi
if [ "$fails" -gt 0 ]; then
  printf 'layer-entry-unreadable: FAIL (%d of %d assertions)\n' "$fails" "$ASSERTIONS"
  exit 1
fi
printf 'layer-entry-unreadable: PASS (%d assertions)\n' "$ASSERTIONS"
